try {if(Get-Command "DotfileLoaded" -ErrorAction stop){}}
Catch {Invoke-Expression ". $env:userprofile/.dotfiles/windows/source/function.ps1"}
DotfileLoaded

$atomPackageList =
"atom-beautify",
"atom-django",
"atom-html-preview",
"atom-python-virtualenv",
"atom-unsaved-changes",
"autoclose-html",
"autocomplete-python",
"busy-signal",
"docblock-python",
"docblockr",
"editorconfig",
"emmet",
"hey-pane",
"Hydrogen",
"intentions",
"linter",
"linter-pylama",
"linter-ui-default",
"markdown-preview-plus",
"markdown-writer",
"minimap",
"minimap-bookmarks",
"minimap-cursorline",
"minimap-find-and-replace",
"minimap-git-diff",
"minimap-lens",
"minimap-linter",
"minimap-pigments",
"minimap-split-diff",
"pigments",
"python-tools",
"regex-railroad-diagram",
# "regex-tester",
"sort-lines",
"split-diff",
"tablr",
"terminal-plus",
"todo-show",
"zentabs"
